"""Baselines, actuals, equipment usage, maintenance and per-company project numbers

Everything the rebuild added to the schema:

* ``tasks`` gains baseline_start/finish/duration and actual_start/finish, which
  is what makes DCMA checks 9, 11 and 14 and the Baseline Execution Index
  computable at all.
* ``projects`` gains a data_date — an activity is late only with respect to a
  reporting date.
* ``schedule_baselines`` stores a frozen snapshot per revision.
* ``equipment_usage_logs`` and ``maintenance_records`` replace a hardcoded
  utilisation figure with a measurement.
* ``projects.project_number`` moves from a global unique constraint to one
  scoped per company. It was global, so a second tenant importing a schedule
  with the same project code failed outright.
* The indexes the application relies on, which were previously issued as DDL at
  start-up through an API removed in SQLAlchemy 2.0 and so never created.

Revision ID: 0002_rebuild_schema
Revises: 0001_baseline
Create Date: 2026-08-08
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0002_rebuild_schema"
down_revision = "0001_baseline"
branch_labels = None
depends_on = None


def _projects_without_global_unique():
    """The projects table as it was, minus the unnamed UNIQUE(project_number).

    Passed to batch_alter_table as ``copy_from`` so the rebuilt table is built
    from this definition rather than from reflection. Reflection would carry
    the old constraint straight back over.
    """
    return sa.Table(
        "projects",
        sa.MetaData(),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text()),
        sa.Column("project_number", sa.String(length=50)),
        sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id")),
        sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id")),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("budget", sa.Float()),
        sa.Column("location", sa.String(length=200)),
        sa.Column("status", sa.String(length=20)),
        sa.Column(
            "schedule_type",
            sa.Enum("GANTT", "LINEAR", "PULL_PLANNING", name="scheduletype"),
        ),
        sa.Column("azure_project_id", sa.String(length=100)),
        sa.Column("fabric_dataset_id", sa.String(length=100)),
        sa.Column("created_at", sa.DateTime()),
        sa.Column("updated_at", sa.DateTime()),
        sa.PrimaryKeyConstraint("id"),
    )


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('set_at', sa.DateTime(), nullable=True),
    sa.Column('set_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['set_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_baselines', schema=None) as batch_op:
        batch_op.create_index('ix_schedule_baselines_current', ['project_id', 'is_current'], unique=False)
        batch_op.create_index('ix_schedule_baselines_project', ['project_id'], unique=False)

    op.create_table('equipment_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('hours_used', sa.Float(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('fuel_used', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_id', 'usage_date', name='uq_equipment_usage_per_day')
    )
    with op.batch_alter_table('equipment_usage_logs', schema=None) as batch_op:
        batch_op.create_index('ix_equipment_usage_company_date', ['company_id', 'usage_date'], unique=False)
        batch_op.create_index('ix_equipment_usage_equipment_date', ['equipment_id', 'usage_date'], unique=False)
        batch_op.create_index('ix_equipment_usage_project', ['project_id'], unique=False)

    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_type', sa.Enum('PREVENTIVE', 'CORRECTIVE', 'EMERGENCY', 'INSPECTION', name='maintenancetype'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', 'CANCELLED', name='maintenancestatus'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('work_performed', sa.Text(), nullable=True),
    sa.Column('labour_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('parts_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('downtime_hours', sa.Float(), nullable=True),
    sa.Column('operating_hours_at_service', sa.Float(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.create_index('ix_maintenance_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index('ix_maintenance_equipment', ['equipment_id'], unique=False)
        batch_op.create_index('ix_maintenance_scheduled', ['company_id', 'scheduled_date'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_company_timestamp', ['company_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_audit_logs_resource', ['resource_type', 'resource_id'], unique=False)
        batch_op.create_index('ix_audit_logs_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('azure_integrations', schema=None) as batch_op:
        batch_op.create_index('ix_azure_integrations_project', ['project_id'], unique=False)

    with op.batch_alter_table('powerbi_integrations', schema=None) as batch_op:
        batch_op.create_index('ix_powerbi_integrations_company', ['company_id'], unique=False)

    # The old schema declared `project_number = Column(String(50), unique=True)`,
    # which produces an UNNAMED unique constraint. Alembic cannot autodetect an
    # unnamed constraint, so left alone the upgrade would add the per-company
    # constraint while the global one carried on enforcing — and the bug it was
    # meant to fix would survive the migration silently.
    #
    # copy_from rebuilds the table from the definition above, which omits it.
    # A batch block with no operations does not trigger a rebuild at all, so
    # the drop has to happen in the same block as the other changes.
    with op.batch_alter_table(
        'projects', copy_from=_projects_without_global_unique(), schema=None
    ) as batch_op:
        batch_op.add_column(sa.Column('data_date', sa.Date(), nullable=True))
        batch_op.create_index('ix_projects_company', ['company_id'], unique=False)
        batch_op.create_index('ix_projects_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index('ix_projects_created_by', ['created_by'], unique=False)
        batch_op.create_unique_constraint('uq_project_number_per_company', ['company_id', 'project_number'])

    with op.batch_alter_table('resource_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_resource_assignments_resource_id', ['resource_id'], unique=False)
        batch_op.create_index('ix_resource_assignments_task_id', ['task_id'], unique=False)

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index('ix_resources_project', ['project_id'], unique=False)

    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.create_index('ix_task_dependencies_predecessor_task_id', ['predecessor_task_id'], unique=False)
        batch_op.create_index('ix_task_dependencies_task_id', ['task_id'], unique=False)
        batch_op.create_unique_constraint('uq_task_dependency_pair', ['task_id', 'predecessor_task_id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baseline_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('baseline_finish', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('baseline_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('actual_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('actual_finish', sa.Date(), nullable=True))
        batch_op.create_index('ix_tasks_parent', ['parent_task_id'], unique=False)
        batch_op.create_index('ix_tasks_project', ['project_id'], unique=False)
        batch_op.create_index('ix_tasks_project_actual_finish', ['project_id', 'actual_finish'], unique=False)
        batch_op.create_index('ix_tasks_project_start', ['project_id', 'start_date'], unique=False)
        batch_op.create_index('ix_tasks_project_status', ['project_id', 'status'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_company', ['company_id'], unique=False)
        batch_op.create_index('ix_users_company_role', ['company_id', 'role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_company_role')
        batch_op.drop_index('ix_users_company')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_project_status')
        batch_op.drop_index('ix_tasks_project_start')
        batch_op.drop_index('ix_tasks_project_actual_finish')
        batch_op.drop_index('ix_tasks_project')
        batch_op.drop_index('ix_tasks_parent')
        batch_op.drop_column('actual_finish')
        batch_op.drop_column('actual_start')
        batch_op.drop_column('baseline_duration')
        batch_op.drop_column('baseline_finish')
        batch_op.drop_column('baseline_start')

    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.drop_constraint('uq_task_dependency_pair', type_='unique')
        batch_op.drop_index('ix_task_dependencies_task_id')
        batch_op.drop_index('ix_task_dependencies_predecessor_task_id')

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index('ix_resources_project')

    with op.batch_alter_table('resource_assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_resource_assignments_task_id')
        batch_op.drop_index('ix_resource_assignments_resource_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('uq_project_number_per_company', type_='unique')
        batch_op.drop_index('ix_projects_created_by')
        batch_op.drop_index('ix_projects_company_status')
        batch_op.drop_index('ix_projects_company')
        batch_op.drop_column('data_date')

    with op.batch_alter_table('powerbi_integrations', schema=None) as batch_op:
        batch_op.drop_index('ix_powerbi_integrations_company')

    with op.batch_alter_table('azure_integrations', schema=None) as batch_op:
        batch_op.drop_index('ix_azure_integrations_project')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_user_id')
        batch_op.drop_index('ix_audit_logs_resource')
        batch_op.drop_index('ix_audit_logs_company_timestamp')

    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.drop_index('ix_maintenance_scheduled')
        batch_op.drop_index('ix_maintenance_equipment')
        batch_op.drop_index('ix_maintenance_company_status')

    op.drop_table('maintenance_records')
    with op.batch_alter_table('equipment_usage_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_equipment_usage_project')
        batch_op.drop_index('ix_equipment_usage_equipment_date')
        batch_op.drop_index('ix_equipment_usage_company_date')

    op.drop_table('equipment_usage_logs')
    with op.batch_alter_table('schedule_baselines', schema=None) as batch_op:
        batch_op.drop_index('ix_schedule_baselines_project')
        batch_op.drop_index('ix_schedule_baselines_current')

    op.drop_table('schedule_baselines')
    # ### end Alembic commands ###
