"""Record which template a project was created from

blueprints/project_templates.py set project.template_used on every project it
created from a template, but no such column existed -- SQLAlchemy kept it as a
transient attribute and discarded it at commit, so the provenance was silently
lost. The "my templates" page, which filters on it, raised AttributeError.

Revision ID: 0003_project_template_used
Revises: 0002_rebuild_schema
Create Date: 2026-08-09 09:10:46.849096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003_project_template_used'
down_revision = '0002_rebuild_schema'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_used', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_projects_template_used'), ['template_used'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_template_used'))
        batch_op.drop_column('template_used')

    # ### end Alembic commands ###
